name: Enviar Alerta en Commit
on:
  push:
    branches:
      - main 

jobs:
  send-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout el código
        uses: actions/checkout@v2

      - name: Obtener número del commit
        id: commit_number
        run: echo "::set-output name=commit_num::$(git rev-list --count HEAD)"

      - name: Enviar Alerta con número de commit
        run: |
          commit_num=${{ steps.commit_number.outputs.commit_num }}
          echo "Se ha realizado un nuevo commit en el repositorio. Número de commit: $commit_num"
